# -*- coding: utf-8 -*-
"""NumpyHW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-pjbQ9_lseBW3aMSf3wsHJPatQ08OuW
"""

import numpy as np

a = [[5, 1, -2, 0],
     [0, 3, 4, 3],
     [2, 3, 1, 1]]
     
b = [[1, -3],
     [2, -2],
     [3, -1],
     [0, 0]]

def no_numpy_mult(first, second):
    string = len(second)
    cell = len(first)
    r2 = len(second[0])
    res = [[0 for i in range(r2)] for j in range(cell)]
    for i in range(cell):
      for j in range(r2):
        for k in range(string):
          res[i][j] += first[i][k] * second[k][j]
    return res

print(no_numpy_mult(a, b))

def numpy_mult(first, second):
  res = np.dot(a, b)
  return res

print (numpy_mult(a, b))

